"""initial schema

Revision ID: d74739dc082b
Revises: 
Create Date: 2026-07-09 10:04:52.542381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74739dc082b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('one_admin_only', 'admin', [sa.literal_column('(true)')], unique=True)
    op.create_table('license_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single', 'lab', name='license_type'), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('max_seats', sa.Integer(), server_default='1', nullable=False),
    sa.Column('bought_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'single' AND max_seats = 1) OR (type = 'lab' AND max_seats >= 1)", name='chk_seat_cap'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_group_id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=255), nullable=False),
    sa.Column('machine_fingerprint_hash', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('created', 'activated', 'expired', name='seat_status'), server_default='created', nullable=False),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expired_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_group_id'], ['license_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_key')
    )
    op.create_index('uq_group_machine', 'license_seat', ['license_group_id', 'machine_fingerprint_hash'], unique=True, postgresql_where=sa.text('machine_fingerprint_hash IS NOT NULL'))
    op.create_table('lab_shared_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_group_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_seat_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['license_group_id'], ['license_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_seat_id'], ['license_seat.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_shared_file_group', 'lab_shared_file', ['license_group_id'], unique=False)
    # ### end Alembic commands ###

    # Seat-cap enforcement: not autogenerated, added by hand.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION enforce_seat_limit() RETURNS TRIGGER AS $$
        DECLARE
            v_max_seats  INTEGER;
            v_used_seats INTEGER;
        BEGIN
            SELECT max_seats INTO v_max_seats FROM license_group WHERE id = NEW.license_group_id;

            SELECT COUNT(*) INTO v_used_seats
            FROM license_seat
            WHERE license_group_id = NEW.license_group_id
              AND status != 'expired';

            IF v_used_seats >= v_max_seats THEN
                RAISE EXCEPTION 'Seat limit (%) reached for license_group_id %', v_max_seats, NEW.license_group_id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_enforce_seat_limit
        BEFORE INSERT ON license_seat
        FOR EACH ROW EXECUTE FUNCTION enforce_seat_limit();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_enforce_seat_limit ON license_seat;")
    op.execute("DROP FUNCTION IF EXISTS enforce_seat_limit();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lab_shared_file_group', table_name='lab_shared_file')
    op.drop_table('lab_shared_file')
    op.drop_index('uq_group_machine', table_name='license_seat', postgresql_where=sa.text('machine_fingerprint_hash IS NOT NULL'))
    op.drop_table('license_seat')
    op.drop_table('license_group')
    op.drop_index('one_admin_only', table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
